package markov

import "strings"

// Generator is an interface for generating strings with a chain
type Generator interface {
	Generate(c *Chain, n int) string
}

// WordGenerator generates a specified number of words from a markov chain
type WordGenerator struct{}

// SentenceGenerator generates a specified number of sentences from a markov chain
type SentenceGenerator struct{}

// Generate returns a randomly generated string on n words from the chain
func (g WordGenerator) Generate(c *Chain, n int) string {
	p := make(prefix, c.PrefixLen)
	var words []string
	for i := 0; i < n; i++ {
		next := c.getWord(p.toString())
		for next == "" {
			// No more options. Shorten prefix
			p.reduce()
			next = c.getWord(p.toString())
		}
		words = append(words, next)
		p.shift(next)
	}

	// Capitalize first word
	if len(words) != 0 {
		words[0] = strings.Title(words[0])
	}

	return strings.Join(words, " ")
}

// Generate creates a randomly generated string of n sentences from the chain
func (g SentenceGenerator) Generate(c *Chain, n int) string {
	return "Generated by the sentence generator"
}
