// Code generated by "stringer -type=DataSource"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[reddit-0]
	_ = x[text-1]
}

const _DataSource_name = "reddittext"

var _DataSource_index = [...]uint8{0, 6, 10}

func (i DataSource) String() string {
	if i < 0 || i >= DataSource(len(_DataSource_index)-1) {
		return "DataSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSource_name[_DataSource_index[i]:_DataSource_index[i+1]]
}
